name: My Workflow

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Say Hello
        run: |
          echo "Step 1"
          echo "Step 2"
          echo "Step 3"